/*import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:csv/csv.dart';
import 'package:share_plus/share_plus.dart';
import 'package:flutter/services.dart' show rootBundle;

class ExportHelper {
  /// 🖨 Generate and share PDF report with logo + app name
  static Future<void> exportToPDF(List<Map<String, dynamic>> results) async {
    final pdf = pw.Document();

    // Load logo from assets
    final logoBytes = await rootBundle.load('assets/image/logo.png');
    final logo = pw.MemoryImage(logoBytes.buffer.asUint8List());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (context) => [
          // Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.center,
            children: [
              pw.Image(logo, height: 60),
              pw.SizedBox(width: 12),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Ethiopian Exam App',
                    style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue800,
                    ),
                  ),
                  pw.Text(
                    'Exam Results Summary',
                    style: const pw.TextStyle(
                      fontSize: 14,
                      color: PdfColors.grey600,
                    ),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 24),

          // Results table
          pw.TableHelper.fromTextArray(
            headers: ['Exam', 'Subject', 'Score (%)', 'Date'],
            data: results.map((e) {
              return [
                e['examTitle'] ?? '',
                e['subject'] ?? '',
                (e['score'] ?? 0).toStringAsFixed(1),
                e['dateTaken'] ?? '',
              ];
            }).toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
            cellAlignment: pw.Alignment.centerLeft,
            cellStyle: const pw.TextStyle(fontSize: 12),
            border: null,
          ),

          pw.SizedBox(height: 20),
          pw.Divider(),
          pw.Text(
            'Generated by Ethiopian Exam App © ${DateTime.now().year}',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey700,
            ),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );

    // Save PDF
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/exam_results.pdf');
    await file.writeAsBytes(await pdf.save());

    // Share
    await Share.shareXFiles([XFile(file.path)], text: '📄 Ethiopian Exam Results PDF');
  }

  /// 📊 Generate and share CSV report
  static Future<void> exportToCSV(List<Map<String, dynamic>> results) async {
    List<List<dynamic>> rows = [
      ['Exam', 'Subject', 'Score (%)', 'Date'],
    ];

    for (var e in results) {
      rows.add([
        e['examTitle'] ?? '',
        e['subject'] ?? '',
        (e['score'] ?? 0).toStringAsFixed(1),
        e['dateTaken'] ?? '',
      ]);
    }

    String csvData = const ListToCsvConverter().convert(rows);

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/exam_results.csv');
    await file.writeAsString(csvData);

    await Share.shareXFiles([XFile(file.path)], text: '📊 Ethiopian Exam Results CSV');
  }
}*/
